<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFGl2MNq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFGl2MNq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFGl2MNq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFGl2MNq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFGl2MNq\App_KernelDevDebugContainer([
    'container.build_hash' => 'FGl2MNq',
    'container.build_id' => '8bee8557',
    'container.build_time' => 1604595294,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFGl2MNq');
